# Generated by Django 4.1.1 on 2022-11-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='availability',
            field=models.IntegerField(choices=[(0, 'available'), (1, 'sold'), (2, 'taken'), (3, 'full')], default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='availability',
            field=models.IntegerField(choices=[(0, 'available'), (1, 'sold'), (2, 'taken'), (3, 'full')], default=0),
        ),
        migrations.AlterField(
            model_name='land',
            name='availability',
            field=models.IntegerField(choices=[(0, 'available'), (1, 'sold'), (2, 'taken'), (3, 'full')], default=0),
        ),
    ]
