# Generated by Django 4.1.1 on 2022-11-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realest_app', '0002_alter_car_availability_alter_house_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_car',
            field=models.ImageField(default='car.png', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_house',
            field=models.ImageField(default='house.png', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_land',
            field=models.ImageField(default='land.png', upload_to='Images/'),
        ),
    ]
