# Generated by Django 4.1.1 on 2022-11-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realest_app', '0003_alter_car_image_car_alter_house_image_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_car',
            field=models.ImageField(blank=True, default='Images/car.png', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_house',
            field=models.ImageField(default='Images/house.png', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image_land',
            field=models.ImageField(blank=True, default='Images/land.png', upload_to='Images/'),
        ),
    ]
