# Generated by Django 4.1.1 on 2022-11-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realest_app', '0004_alter_car_image_car_alter_house_image_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='land',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
