# Generated by Django 4.1.1 on 2022-11-13 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realest_app', '0005_alter_car_price_alter_house_price_alter_land_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='NumberOfBathroom',
            new_name='NumberOfBathrooms',
        ),
    ]
