# Generated by Django 4.1.1 on 2022-11-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realest_app', '0006_rename_numberofbathroom_house_numberofbathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='car'),
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(default='house'),
        ),
        migrations.AddField(
            model_name='land',
            name='description',
            field=models.TextField(default='house'),
        ),
    ]
